pub(crate) mod add;
pub(crate) mod clean;
pub(crate) mod completions;
pub(crate) mod doctor;
pub(crate) mod init;
pub(crate) mod list;
pub(crate) mod lock;
pub(crate) mod remove;
pub(crate) mod self_update;
mod source_edit;
pub(crate) mod sync;
pub(crate) mod uninstall;
